# Generated by Django 5.1.4 on 2024-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodorobackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allocated_hours',
            field=models.FloatField(help_text='Number of hours allocated for the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.FloatField(default=0.0, help_text='Number of hours spent on the task'),
        ),
    ]
